# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = true

# 10 milliseconds timeout
scan_timeout = 10

[character]
success_symbol = "[▶](bold green)"
error_symbol = "[▶](bold red)"

[directory]
style = "bold yellow"

[git_branch]
format ="[$symbol$branch(:$remote_branch)]($style) "
style = "bold #ff6fff"

[aws]
format = "[$symbol($profile)\\($region\\)]($style) "
symbol = '☁️'
[aws.region_aliases]
ap-northeast-1 = "an1"

[gcloud]
format = "[$symbol$project(\\($region\\))]($style) "
symbol = '☁️'
[gcloud.region_aliases]
us-central1 = "uc1"
asia-northeast1 = "an1"
